### ISSUE TITLE
part of the result has purple dots 

### ISSUE THREAD

**Issue by mwsunshine** [liyucs/RAGNet#1]
Dear author,

Thanks in advance for your great work and effort!

I did some tests with my own images, and had some problems.  The main problem is about the result of de-reflection images.

As you can see, some parts of the images have obvious purple dots, I am wondering whether these errors are caused by my side or they are the normal outputs.

If the answer is the latter, could you please explain why these purple dots are generated and are you going to reduce this side effects in the future? If the answer is the former, could you please inform me of the correct method to use your model? What I did is to replace my images with the images in folder  ./testsets/real45 and run python test.py

Samples in my test are showed below:
![8_b](https://user-images.githubusercontent.com/13763085/105123154-8db63680-5b12-11eb-8f6f-3d13721d2275.jpg)
![8_t_mark](https://user-images.githubusercontent.com/13763085/105123173-9575db00-5b12-11eb-834a-42ee8a855ae8.jpg)

**Comment by liyucs** [comment]
Thank you for your attention to our work!
You can avoid this problem by resizing it before testing (e.g.,300*400). The result is as follows: 
![0_t](https://user-images.githubusercontent.com/70555619/105158515-033cf980-5b49-11eb-8d5f-6bb5b78fb9e9.png)

We didn't meet similar problem in our tests. By testing this image using another checkpoint in a different epoch, the problem didn't show up either. We will keep watching the issue.
Besides, the provided checkpoint was trained with data in relatively low resolution (224*224). There is a domain gap between datasets. Better performance could be achieved by finetuning the model with more images from your target domain (scenario/resolution).

**Comment by mwsunshine** [comment]
> Thank you for your attention to our work!
> You can avoid this problem by resizing it before testing (e.g.,300*400). The result is as follows:
> ![0_t](https://user-images.githubusercontent.com/70555619/105158515-033cf980-5b49-11eb-8d5f-6bb5b78fb9e9.png)
> 
> We didn't meet similar problem in our tests. By testing this image using another checkpoint in a different epoch, the problem didn't show up either. We will keep watching the issue.
> Besides, the provided checkpoint was trained with data in relatively low resolution (224*224). There is a domain gap between datasets. Better performance could be achieved by finetuning the model with more images from your target domain (scenario/resolution).

Thank you for your quick response!

I could understand the size of outputs depends heavily on the size of training, so I resized my image to the resolution of 400x300 and rerun the code. However, It's quite strange my result is very different from the one you showed:
![3_t](https://user-images.githubusercontent.com/13763085/105269180-658c0d80-5bce-11eb-8cb7-ad71cc3e6886.png)
What I did is resize the image to 400x300 -> move the image to the folder ./testsets/real45 -> run python test.py. 
I use the model provided by the webside(pretrain.pth)

**Comment by liyucs** [comment]
I also used the model released to get the result I showed. There are two ways to get it:
(1) resize input image to 400*300 first, you can get input image as bellow, then move the image to the folder ./testsets/real45 -> run python test.py.
![0_b](https://user-images.githubusercontent.com/70555619/105298816-64baa200-5bf5-11eb-8173-978822ea5708.png)
(2) put the image in original size to the folder ./testsets/real45 -> change line 191 to 
test_dataset_real45 = TestDataset(image_list_real45,gt_list_real45,transform=True,if_GT=False) -> run python test.py.

**Comment by mwsunshine** [comment]
> I also used the model released to get the result I showed. There are two ways to get it:
> (1) resize input image to 400*300 first, you can get input image as bellow, then move the image to the folder ./testsets/real45 -> run python test.py.
> ![0_b](https://user-images.githubusercontent.com/70555619/105298816-64baa200-5bf5-11eb-8173-978822ea5708.png)
> (2) put the image in original size to the folder ./testsets/real45 -> change line 191 to
> test_dataset_real45 = TestDataset(image_list_real45,gt_list_real45,transform=True,if_GT=False) -> run python test.py.

I get the reason why our results are different:
Your input is slightly different from mine(you can compare yours with my uploaded image). With your input, I can get the same result as yours. 

I checked whether it is the format that matters for the difference. The answer is no. I used the second method as you mentioned, the results are still different.

I think the slight difference for the inputs is the root cause. Maybe you can try the input following:
![066_0_1280x960_1](https://user-images.githubusercontent.com/13763085/105326529-ce907700-5c08-11eb-9e48-4a00e349a33f.jpg)

**Comment by liyucs** [comment]
I can get the result I uploaded with both methods 1&2. The resizing and saving codes I used are the same as those in line 95 and line 133 of test.py respectively.
The version of OpenCV is '4.1.0', maybe you should use the same version as mine to get the result. Besides, the image you uploaded is in jpg (23.5k), saving the image directly in png (224.6k) after resizing may work.

**Comment by mwsunshine** [comment]
> I can get the result I uploaded with both methods 1&2. The resizing and saving codes I used are the same as those in line 95 and line 133 of test.py respectively.
> The version of OpenCV is '4.1.0', maybe you should use the same version as mine to get the result. Besides, the image you uploaded is in jpg (23.5k), saving the image directly in png (224.6k) after resizing may work.

Sure, I will check with the way you did! Thank you for your information!
I will close this question
