### ISSUE TITLE
What is Fusion Ratio?

### ISSUE THREAD

**Issue by Pushkar2307** [liyucs/RAGNet#2]
Hi, thank you for sharing this amazing work!

Can you explain what is the purpose of 'Fusion Ratio" while preparing dataset in the code shared?

**Comment by liyucs** [comment]
Thank you for your attention to our work!
Fusion Ratio is the ratio between the synthetic/real data we used during training.

**Comment by Pushkar2307** [comment]
Okay Thank you!

So if I was training with just synthetic data, should I put the fusion ratio of real data to zero?

**Comment by liyucs** [comment]
Yes, or you can replace 'train_fusion_dataset' from line 169 with 'train_refsyn_dataset' from line 165 in solver.py.
